from __future__ import annotations

from collections.abc import Generator, Iterable, Mapping, MutableMapping
from typing import overload


class HatTrieMap[T] (MutableMapping[bytes, T]):
    def __init__(self, items: Mapping[bytes, T] | Iterable[tuple[bytes, T]]) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> HatTrieMap[T]: ...
    def count(self, key: bytes) -> int: ...
    def count_prefix(self, prefix: bytes) -> int: ...
    def equal_prefix_range(self, prefix: bytes) -> Generator[tuple[bytes, T]]: ...
    def empty(self) -> bool: ...
    def erase_prefix(self, prefix: bytes) -> int: ...
    def get[DefT](self, key: bytes, value: DefT = None) -> T | DefT: ...
    def insert(self, key: bytes, value: T) -> bool: ...
    def items(self) -> Generator[tuple[bytes, T]]: ...
    def keys(self) -> Generator[bytes]: ...
    def longest_prefix(self, key: bytes) -> Generator[tuple[bytes, T]]: ...
    def max_key_size(self) -> int: ...
    def max_size(self) -> int: ...
    @overload
    def pop[DefT](self, key: bytes) -> T: ...
    @overload
    def pop[DefT](self, key: bytes, default: DefT) -> T | DefT: ...
    def setdefault(self, key: bytes, value: T) -> T: ...
    def shrink_to_fit(self) -> None: ...
    def size(self) -> int: ...
    def to_dict(self) -> dict[bytes, T]: ...
    def update(self, map: Mapping[bytes, T] | Iterable[tuple[bytes, T]]) -> None: ...
    def values(self) -> Generator[T]: ...
    def __contains__(self, other: bytes, /) -> bool: ...
    def __delitem__(self, other: bytes, /) -> None: ...
    def __getitem__(self, key: bytes, /) -> T: ...
    def __getstate__(self) -> Any: ...
    def __iter__(self) -> Generator[bytes]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, key: bytes, object: T, /) -> None: ...
    def __setstate__(self, state: Any, /) -> HatTrieMap[T]: ...
