from __future__ import annotations

from collections.abc import Generator, Mapping
from typing import overload


class HatTrieMap[T]:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> HatTrieMap[T]: ...
    def count(self, stringkey: bytes) -> int: ...
    def empty(self) -> bool: ...
    def erase_prefix(self, stringprefix: bytes) -> int: ...
    def get[DefT](self, key: bytes, value: DefT = None) -> T | DefT: ...
    def insert(self, stringkey: bytes, value: T) -> bool: ...
    def items(self) -> Generator[tuple[bytes, T]]: ...
    def keys(self) -> Generator[bytes]: ...
    def longest_prefix(self, stringkey: bytes) -> Generator[tuple[bytes, T]]: ...
    def max_key_size(self) -> int: ...
    def max_size(self) -> int: ...
    @overload
    def pop[DefT](self, key: bytes) -> T: ...
    @overload
    def pop[DefT](self, key: bytes, default: DefT) -> T | DefT: ...
    def setdefault(self, stringkey: bytes, value: T) -> T: ...
    def shrink_to_fit(self) -> None: ...
    def size(self) -> int: ...
    def to_dict(self) -> dict[bytes, T]: ...
    def update(self, map: Mapping[bytes, T]) -> None: ...
    def values(self) -> Generator[T]: ...
    def __contains__(self, other: bytes) -> bool: ...
    def __delitem__(self, other: bytes) -> None: ...
    def __getitem__(self, index: bytes) -> T: ...
    def __getstate__(self) -> Any: ...
    def __iter__(self) -> Generator[bytes]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, index: bytes, object: T) -> None: ...
    def __setstate__(self, state: Any) -> HatTrieMap[T]: ...
